# Generated by Django 5.1.2 on 2024-11-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank_loan',
            fields=[
                ('Name', models.CharField(max_length=10)),
                ('loan_amount', models.IntegerField(primary_key='Refno', serialize=False)),
                ('mobile_number', models.FloatField()),
                ('DoB', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
